
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zshotocsmvrgkcmofrks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzaG90b2NzbXZyZ2tjbW9mcmtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTA3NzEsImV4cCI6MjA2MTc2Njc3MX0.SQNHhHTv4Wg8BhxY0HUwGmvjDu0aL3r9U--v_hgGCZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
